# Server port
server.port=8080

# View resolver configuration for JSP
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# H2 Database configuration
# spring.datasource.url=jdbc:h2:mem:userdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

spring.datasource.url=jdbc:h2:mem:coursedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password= 
spring.sql.init.schema-locations=classpath:/data.sql
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.sql.init.data-locations=classpath:/data.sql
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA configuration
# spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always

spring.jpa.show-sql=true